export enum NotificationCommandName {
  taskStatusChange = 'Смена статуса',
  priorityChange = 'Смена приоритета',
  priorityCancel = 'Отмена приоритета',
  descriptionEdit = 'Редактирование описания',
  taskTagUnassign = 'Отмена тега у сущности',
  taskTagAssign = 'Добавление тега к сущности',
  timeEndChange = 'Изменение времени окончания',
  timeStartChange = 'Изменение времени начала',
  taskRoleUnassign = 'Снятие с роли',
  taskTitleChange = 'Редактирование заголовка',
  taskRoleAssign = 'Назначение роли',
  taskStorageFileAssign = 'Добавление файла',
  taskStorageFileUnassign = 'Удаление файла',
  taskCheckListAssign = 'Добавление чеклиста к задаче',
  taskCheckListUnassign = 'Удаление чеклиста у задачи',
  checkListTitleChange = 'Изменение заголовка у чеклиста',
  checkListItemCreate = 'добавил(а) новый пункт в чек-лист ',
  checkListItemDelete = 'Удаление пункта чеклиста',
  checkListItemChangeComplete = 'Изменение состояния пункта у чеклиста',
}

export enum NotificationMessageToShow {
  taskStatusChange = 'сменил(а) статус задачи',
  priorityChange = 'Смена приоритета',
  priorityCancel = 'удалил(а) приоритет',
  descriptionEdit = 'изменил(а) описание',
  taskTagUnassign = 'удалил(а) метки',
  taskTagAssign = 'добавил(а) новые метки',
  timeEndChange = 'Изменение времени окончания',
  timeStartChange = 'Изменение времени начала',
  taskRoleUnassign = 'Снятие с роли',
  taskTitleChange = 'изменил(а) заголовок задачи',
  taskRoleAssign = 'добавил(а) новых участников ',
  taskStorageFileAssign = 'Добавление файла',
  taskStorageFileUnassign = 'удалил(а) вложение',
  taskCheckListAssign = 'добавил(а) чек-лист ',
  taskCheckListUnassign = 'удалил(а) чек-лист',
  checkListTitleChange = 'изменил(а) название чек-листа',
  checkListItemCreate = 'Добавление пункта к чеклисту',
  checkListItemDelete = 'удалил(а) пункт в чеклисте ',
  checkListItemChangeComplete = 'Изменение состояния пункта у чеклиста',
}

export const NOTIFICATION_COUNT_INCREMENT = 20;
